#ifndef ASSETS_SPRITES_SCIFIRTS_SPRITESHEET_GENERATED_H_
#define ASSETS_SPRITES_SCIFIRTS_SPRITESHEET_GENERATED_H_
// AUTO-GENERATED by sprite_editor -- do not edit by hand.
#include <string_view>

#include "graphics/sprite_rect.h"

namespace api::graphics::sprites::scifirts_spritesheet {

inline constexpr std::string_view kTexture = "scifiRTS_spritesheet.png";

inline constexpr SpriteRect kEmpty1{ .x=0, .y=0, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite1{ .x=64, .y=0, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite2{ .x=128, .y=0, .w=64, .h=54, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite3{ .x=192, .y=0, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite4{ .x=256, .y=0, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite5{ .x=320, .y=0, .w=44, .h=44, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kEmpty2{ .x=0, .y=64, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite9{ .x=64, .y=64, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite10{ .x=128, .y=54, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite11{ .x=192, .y=64, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite12{ .x=256, .y=64, .w=62, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite13{ .x=318, .y=64, .w=44, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite16{ .x=0, .y=128, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite17{ .x=64, .y=128, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite18{ .x=128, .y=118, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite19{ .x=192, .y=128, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite20{ .x=256, .y=128, .w=56, .h=56, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite24{ .x=0, .y=192, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite25{ .x=64, .y=192, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite26{ .x=128, .y=182, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite27{ .x=192, .y=192, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite28{ .x=256, .y=184, .w=56, .h=56, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite32{ .x=0, .y=256, .w=64, .h=47, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite33{ .x=64, .y=256, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite34{ .x=128, .y=247, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite35{ .x=192, .y=256, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite40{ .x=0, .y=304, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite41{ .x=64, .y=320, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite42{ .x=128, .y=310, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite43{ .x=192, .y=320, .w=64, .h=30, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite48{ .x=0, .y=367, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite49{ .x=64, .y=384, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite50{ .x=128, .y=374, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite51{ .x=192, .y=350, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite56{ .x=0, .y=431, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite57{ .x=64, .y=448, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite58{ .x=128, .y=438, .w=64, .h=64, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite59{ .x=192, .y=414, .w=64, .h=47, .origin_x=32.0f, .origin_y=32.0f };
inline constexpr SpriteRect kSprite42_1{ .x=192, .y=461, .w=60, .h=48, .origin_x=30.0f, .origin_y=24.0f };

}  // namespace api::graphics::sprites::scifirts_spritesheet

#endif  // ASSETS_SPRITES_SCIFIRTS_SPRITESHEET_GENERATED_H_
