#ifndef ASSETS_SPRITES_SCIFIENVIRONMENT_15_GENERATED_H_
#define ASSETS_SPRITES_SCIFIENVIRONMENT_15_GENERATED_H_
// AUTO-GENERATED by sprite_editor -- do not edit by hand.
#include <string_view>

#include "graphics/sprite_rect.h"

namespace api::graphics::sprites::scifienvironment_15 {

inline constexpr std::string_view kTexture = "scifiEnvironment_15.png";

inline constexpr SpriteRect kFull{ .x=0, .y=0, .w=64, .h=64, .origin_x=0.0f, .origin_y=0.0f };

}  // namespace api::graphics::sprites::scifienvironment_15

#endif  // ASSETS_SPRITES_SCIFIENVIRONMENT_15_GENERATED_H_
