#include "header_generator.h"

#include <cctype>
#include <format>
#include <string>
#include <unordered_set>

namespace sprite_editor {
namespace {

bool IsIdentChar(char c) {
  const auto u = static_cast<unsigned char>(c);
  return std::isalnum(u) != 0 || c == '_';
}

char ToLowerChar(char c) {
  return static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
}

char ToUpperChar(char c) {
  return static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
}

std::string ToUpperGuard(std::string_view snake) {
  std::string out;
  out.reserve(snake.size());
  for (const char c : snake) {
    out.push_back(ToUpperChar(c));
  }
  return out;
}

}  // namespace

std::string ToSnakeIdentifier(std::string_view raw) {
  std::string out;
  out.reserve(raw.size());
  bool last_was_underscore = false;
  for (const char c : raw) {
    if (IsIdentChar(c) && c != '_') {
      out.push_back(ToLowerChar(c));
      last_was_underscore = false;
    } else if (!last_was_underscore && !out.empty()) {
      out.push_back('_');
      last_was_underscore = true;
    }
  }
  while (!out.empty() && out.back() == '_') {
    out.pop_back();
  }
  if (out.empty()) {
    out = "sheet";
  }
  if (std::isdigit(static_cast<unsigned char>(out.front())) != 0) {
    out.insert(out.begin(), '_');
  }
  return out;
}

std::string ToPascalIdentifier(std::string_view raw) {
  std::string out;
  out.reserve(raw.size());
  bool start_word = true;
  for (const char c : raw) {
    if (!IsIdentChar(c) || c == '_') {
      start_word = true;
      continue;
    }
    if (start_word) {
      out.push_back(ToUpperChar(c));
      start_word = false;
    } else {
      out.push_back(c);
    }
  }
  if (out.empty()) {
    out = "Sprite";
  }
  if (std::isdigit(static_cast<unsigned char>(out.front())) != 0) {
    out.insert(out.begin(), '_');
  }
  return out;
}

std::string GenerateHeader(const SheetDocument& document,
                           std::string_view sheet_stem) {
  const std::string snake = ToSnakeIdentifier(sheet_stem);
  const std::string guard = std::format("API_GRAPHICS_GENERATED_{}_H_",
                                        ToUpperGuard(snake));

  std::string out;
  out += std::format("#ifndef {}\n#define {}\n", guard, guard);
  out += "// AUTO-GENERATED by sprite_editor -- do not edit by hand.\n";
  out += "#include <string_view>\n\n";
  out += "#include \"graphics/sprite_rect.h\"\n\n";
  out += std::format("namespace api::graphics::sprites::{} {{\n\n", snake);
  out += std::format(
      "inline constexpr std::string_view kTexture = \"{}\";\n\n",
      document.texture);

  std::unordered_set<std::string> used;
  for (const auto& sprite : document.sprites) {
    std::string ident = std::format("k{}", ToPascalIdentifier(sprite.name));
    std::string candidate = ident;
    int suffix = 1;
    while (!used.insert(candidate).second) {
      candidate = std::format("{}_{}", ident, suffix);
      ++suffix;
    }
    out += std::format(
        "inline constexpr SpriteRect {}{{ .x={}, .y={}, .w={}, .h={}, "
        ".origin_x={:.1f}f, .origin_y={:.1f}f }};\n",
        candidate, sprite.x, sprite.y, sprite.w, sprite.h, sprite.origin_x,
        sprite.origin_y);
  }

  out += std::format("\n}}  // namespace api::graphics::sprites::{}\n\n", snake);
  out += std::format("#endif  // {}\n", guard);
  return out;
}

}  // namespace sprite_editor
